### ISSUE TITLE
n_jobs issue in classify

### ISSUE THREAD

**Issue by bpstewar** [jgrss/mpglue#5]
I have just finished raster_sample and am trying to run classify and get a weird error about a keyword n_jobs

```
(base) root@7e155d7d6139:~# classify -i /mnt/work/input/output/fullVrt__BD1_BK8_SC8-16-32-64_TRdmp-gabor-grad-hog-lac-lsr-mean-orb-pantex-saliency-seg-sfs-fourier.vrt -o /mnt/work/input/output/classified_image.tif -s /mnt/work/training/training_sites_points__fullVrt__BD1_BK8_SC8-16-32-64_TRdmp-gabor-grad-hog-lac-lsr-mean-orb-pantex-saliency-seg-sfs-fourier_SAMPLES.txt --jobs 6
13:24:40:INFO:125:classify.main:
Start date & time --- (Wed May 30 13:24:40 2018)

Traceback (most recent call last):
  File "/opt/conda/envs/spfeasenv/bin/classify", line 11, in <module>
    load_entry_point('MpGlue==0.1.9', 'console_scripts', 'classify')()
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/MpGlue-0.1.9-py2.7-linux-x86_64.egg/mpglue/classification/classify.py", line 142, in main
    be_quiet=args.be_quiet, n_jobs=args.n_jobs)
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/MpGlue-0.1.9-py2.7-linux-x86_64.egg/mpglue/classification/classify.py", line 28, in construct
    self.cl.construct_model(**kwargs)
TypeError: construct_model() got an unexpected keyword argument 'n_jobs'
```

**Comment by jgrss** [comment]
This should now be fixed. Please pull the latest version.

**Comment by jgrss** [comment]
I am looking into this...

Which version is installed?

```bash
python -c "import mpglue as gl;print(gl.__version__)"
```

**Comment by jgrss** [comment]
@bpstewar pull the latest code and check the version after installing:

```bash
classify --version
```
