### ISSUE TITLE
Installation unsuccessful

### ISSUE THREAD

**Issue by d3netxer** [jgrss/mpglue#8]
Any help or tips? I tried to install using the 2nd installation instructions using Ubuntu 18.04

$ pip install v0.1.2.tar.gz 
```
Processing ./v0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wj2j2xgw-build/setup.py", line 109, in <module>
        setup_package()
      File "/tmp/pip-wj2j2xgw-build/setup.py", line 98, in setup_package
        ext_modules=cythonize(get_pyx_list(), include_dirs=[np.get_include()]),
      File "/home/vagrant/environments/spfeas1/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 956, in cythonize
        c_options = CompilationOptions(**options)
      File "/home/vagrant/environments/spfeas1/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 561, in __init__
        raise ValueError(message)
    ValueError: got unknown compilation option, please remove: include_dirs
    ```
- Cython version 0.29.5
- numpy version 1.16.1
- Python version 3.6.7

**Comment by d3netxer** [comment]
I replaced this line:

```
ext_modules=cythonize(get_pyx_list(), include_dirs=[np.get_include()]),
```
with
```
ext_modules=cythonize(get_pyx_list(),include_path=[np.get_include()])
```

and it got through this part
